apiVersion: apps/v1
kind: Deployment
metadata:
  name: labtwin-dmitescu-deployment
  labels:
    app: labtwin-dmitescu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labtwin-dmitescu
  template:
    metadata:
      labels:
        app: labtwin-dmitescu
    spec:
      containers:
      - name: labtwin-dmitescu
        image: labtwin:1.0
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 1
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: labtwin-dmitescu-service
spec:
  selector:
    app: labtwin-dmitescu
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
